sudo : required
addons:
  chrome: stable
language : node_js
node_js :
 - stable
install:
 - npm install
script:
 - ng test --watch=false --code-coverage
 - ng test ng-documentations --watch=false --code-coverage

before_script:
  - npm install -g @angular/cli